### PR TITLE
chore(README): update file content

### PR DESCRIPTION
**Pull request by s-rigaud**
Add bages with tech stack for each project.

Preview: https://github.com/s-rigaud/awesome-vuetify/tree/add-version-badges

I'm hesitating between [inline badges](https://github.com/s-rigaud/awesome-vuetify/tree/add-version-badges-inline) and new line bades (this PR) as I didn't manage to vertiacally align badges for the inline version.

The icon should be updated pretty soon : https://github.com/simple-icons/simple-icons/pull/9445

### CODE REVIEW

**Comment by johnleider** [comment]
What are your thoughts on grouping things by Vuetify version? I like the idea of identifying them, but it's hard to read.

**Comment by s-rigaud** [comment]
Might be  a good thing, especially since examples using Vuetify 1 are not so great neither researched by users. I will remove them

**Review by johnleider — COMMENTED** [review]
Looks good. The only issue I see is the incorrect logo used here:

image

It should be like the one at the top of the file.

**Comment by s-rigaud** [comment]
Simply waiting for this PR to be merged then https://github.com/simple-icons/simple-icons/pull/9445

**Comment by johnleider** [comment]
Can we use this logo instead?

https://vuetifyjs.com/en/resources/brand-kit/

image

**Comment by s-rigaud** [comment]
I used a colorised version of the SVG logo. I find the result pretty nice

**Review by johnleider — APPROVED** [review]

**Pull request merged**
